[phases.setup]
nixPkgs = ["nodejs-18_x"]

[phases.install]
cmds = ["cd backend && npm ci"]

[phases.build] 
cmds = ["cd backend && echo 'No build step required'"]

[start]
cmd = "cd backend && node server.js"

[variables]
NODE_ENV = "production"